import {
  Anchor,
  At,
  Balloon,
  Bank,
  Barbell,
  Basketball,
  Bell,
  Bicycle,
  Binoculars,
  Book,
  BookOpen,
  Bookmark,
  BowlFood,
  BoxingGlove,
  Briefcase,
  Building,
  BuildingApartment,
  BuildingOffice,
  Buildings,
  Cake,
  Calendar,
  CalendarCheck,
  CalendarDots,
  Camera,
  Chat,
  ChatCircle,
  Check,
  CheckCircle,
  ClipboardText,
  Clock,
  ClockClockwise,
  Cloud,
  Code,
  Coffee,
  Coin,
  Coins,
  Compass,
  Confetti,
  Cpu,
  CreditCard,
  Crown,
  CurrencyDollar,
  CurrencyRub,
  Database,
  Desktop,
  DeviceMobile,
  DeviceTablet,
  Drop,
  Envelope,
  Eye,
  FastForward,
  FilmSlate,
  FilmStrip,
  Fire,
  Flag,
  ForkKnife,
  Football,
  Funnel,
  Gift,
  Globe,
  GraduationCap,
  HandsClapping,
  HandsPraying,
  Hammer,
  Headphones,
  Heart,
  HeartStraight,
  House,
  HouseSimple,
  Hourglass,
  Info,
  Key,
  Laptop,
  Leaf,
  Lightbulb,
  LightbulbFilament,
  Lightning,
  Link,
  List,
  ListChecks,
  Lock,
  LockOpen,
  MagicWand,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Medal,
  Megaphone,
  Microphone,
  MicrophoneStage,
  MoneyWavy,
  Monitor,
  Moon,
  Mountains,
  MusicNote,
  MusicNotes,
  Newspaper,
  Notebook,
  NotePencil,
  PaintBrush,
  PaintBrushBroad,
  PaintBucket,
  Palette,
  Package,
  PaperPlaneTilt,
  Paperclip,
  Pause,
  PauseCircle,
  Pencil,
  PersonSimpleBike,
  PersonSimpleRun,
  PersonSimpleSwim,
  PersonSimpleTaiChi,
  Phone,
  PhoneCall,
  PiggyBank,
  PingPong,
  Pizza,
  Play,
  PlayCircle,
  PlayPause,
  Popcorn,
  Power,
  Presentation,
  PresentationChart,
  Printer,
  PuzzlePiece,
  QrCode,
  Question,
  QuestionMark,
  Racquet,
  Rainbow,
  Receipt,
  Repeat,
  Rewind,
  Robot,
  RocketLaunch,
  Rss,
  Ruler,
  Scissors,
  Screwdriver,
  ShareNetwork,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  SoccerBall,
  Sparkle,
  StackSimple,
  Star,
  StarFour,
  Stop,
  Storefront,
  Student,
  Sun,
  Swatches,
  Tag,
  TelegramLogo,
  TennisBall,
  Terminal,
  TerminalWindow,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  Tree,
  TreePalm,
  Trophy,
  Truck,
  User,
  UserCircle,
  Users,
  UsersFour,
  UsersThree,
  VideoCamera,
  Volleyball,
  Wallet,
  Warning,
  WarningCircle,
  Watch,
  WhatsappLogo,
  WifiHigh,
  Wine,
  Wrench,
  X,
  XCircle,
} from "@phosphor-icons/react";

import type { Icon as PhosphorIconType } from "@phosphor-icons/react";

// Single source of truth: snake-case key → Phosphor component.
// Stored in DB as the snake-case key. Render with weight="duotone".
export const PHOSPHOR_ICONS: Record<string, PhosphorIconType> = {
  // Sport / fitness
  "barbell": Barbell,
  "basketball": Basketball,
  "bicycle": Bicycle,
  "boxing-glove": BoxingGlove,
  "football": Football,
  "medal": Medal,
  "person-bike": PersonSimpleBike,
  "person-run": PersonSimpleRun,
  "person-swim": PersonSimpleSwim,
  "person-taichi": PersonSimpleTaiChi,
  "ping-pong": PingPong,
  "racquet": Racquet,
  "soccer-ball": SoccerBall,
  "tennis-ball": TennisBall,
  "trophy": Trophy,
  "volleyball": Volleyball,

  // Events / celebration / media
  "balloon": Balloon,
  "cake": Cake,
  "camera": Camera,
  "confetti": Confetti,
  "film-slate": FilmSlate,
  "film-strip": FilmStrip,
  "gift": Gift,
  "headphones": Headphones,
  "megaphone": Megaphone,
  "microphone": Microphone,
  "microphone-stage": MicrophoneStage,
  "music-note": MusicNote,
  "music-notes": MusicNotes,
  "play-circle": PlayCircle,
  "popcorn": Popcorn,
  "ticket": Ticket,
  "video-camera": VideoCamera,
  "wine": Wine,

  // Communication
  "at": At,
  "chat": Chat,
  "chat-circle": ChatCircle,
  "envelope": Envelope,
  "paper-plane": PaperPlaneTilt,
  "phone": Phone,
  "phone-call": PhoneCall,
  "share": ShareNetwork,
  "telegram": TelegramLogo,
  "whatsapp": WhatsappLogo,

  // People
  "student": Student,
  "user": User,
  "user-circle": UserCircle,
  "users": Users,
  "users-three": UsersThree,
  "users-four": UsersFour,
  "hands-clapping": HandsClapping,
  "hands-praying": HandsPraying,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,

  // Work / office / education
  "book": Book,
  "book-open": BookOpen,
  "briefcase": Briefcase,
  "clipboard": ClipboardText,
  "graduation-cap": GraduationCap,
  "newspaper": Newspaper,
  "note-pencil": NotePencil,
  "notebook": Notebook,
  "presentation": Presentation,
  "presentation-chart": PresentationChart,
  "printer": Printer,

  // Buildings / places
  "bank": Bank,
  "building": Building,
  "building-apartment": BuildingApartment,
  "building-office": BuildingOffice,
  "buildings": Buildings,
  "house": House,
  "house-simple": HouseSimple,
  "storefront": Storefront,
  "compass": Compass,
  "globe": Globe,
  "map-pin": MapPin,
  "map": MapTrifold,
  "mountains": Mountains,

  // Money
  "coin": Coin,
  "coins": Coins,
  "credit-card": CreditCard,
  "currency-dollar": CurrencyDollar,
  "currency-rub": CurrencyRub,
  "money-wavy": MoneyWavy,
  "piggy-bank": PiggyBank,
  "receipt": Receipt,
  "wallet": Wallet,

  // Tech
  "cloud": Cloud,
  "code": Code,
  "cpu": Cpu,
  "database": Database,
  "desktop": Desktop,
  "device-mobile": DeviceMobile,
  "device-tablet": DeviceTablet,
  "laptop": Laptop,
  "monitor": Monitor,
  "qr-code": QrCode,
  "robot": Robot,
  "rss": Rss,
  "terminal": Terminal,
  "terminal-window": TerminalWindow,
  "wifi": WifiHigh,

  // Time
  "calendar": Calendar,
  "calendar-check": CalendarCheck,
  "calendar-dots": CalendarDots,
  "clock": Clock,
  "clock-back": ClockClockwise,
  "hourglass": Hourglass,
  "timer": Timer,
  "watch": Watch,

  // Nature / weather
  "drop": Drop,
  "fire": Fire,
  "leaf": Leaf,
  "lightning": Lightning,
  "moon": Moon,
  "rainbow": Rainbow,
  "sparkle": Sparkle,
  "star": Star,
  "star-four": StarFour,
  "sun": Sun,
  "tree": Tree,
  "tree-palm": TreePalm,

  // Food / drink
  "bowl-food": BowlFood,
  "coffee": Coffee,
  "fork-knife": ForkKnife,
  "pizza": Pizza,

  // Service / craft / utility
  "anchor": Anchor,
  "binoculars": Binoculars,
  "crown": Crown,
  "hammer": Hammer,
  "lightbulb": Lightbulb,
  "lightbulb-filament": LightbulbFilament,
  "magic-wand": MagicWand,
  "package": Package,
  "paint-brush": PaintBrush,
  "paint-brush-broad": PaintBrushBroad,
  "paint-bucket": PaintBucket,
  "palette": Palette,
  "puzzle-piece": PuzzlePiece,
  "ruler": Ruler,
  "scissors": Scissors,
  "screwdriver": Screwdriver,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "swatches": Swatches,
  "wrench": Wrench,
  "truck": Truck,

  // Heart / emotional
  "heart": Heart,
  "heart-straight": HeartStraight,

  // Status / UI
  "bell": Bell,
  "bookmark": Bookmark,
  "check": Check,
  "check-circle": CheckCircle,
  "eye": Eye,
  "flag": Flag,
  "funnel": Funnel,
  "info": Info,
  "key": Key,
  "link": Link,
  "list": List,
  "list-checks": ListChecks,
  "lock": Lock,
  "lock-open": LockOpen,
  "magnifying-glass": MagnifyingGlass,
  "paperclip": Paperclip,
  "pencil": Pencil,
  "question": Question,
  "question-mark": QuestionMark,
  "shield-check": ShieldCheck,
  "stack": StackSimple,
  "tag": Tag,
  "warning": Warning,
  "warning-circle": WarningCircle,
  "x": X,
  "x-circle": XCircle,

  // Controls
  "fast-forward": FastForward,
  "pause": Pause,
  "pause-circle": PauseCircle,
  "play": Play,
  "play-pause": PlayPause,
  "power": Power,
  "repeat": Repeat,
  "rewind": Rewind,
  "rocket-launch": RocketLaunch,
  "shuffle": Shuffle,
  "stop": Stop,
};

export const PHOSPHOR_NAMES = Object.keys(PHOSPHOR_ICONS);

export function AppIcon({
  name,
  size = 18,
  color,
  className,
  style,
  weight = "duotone",
}: {
  name: string | null | undefined;
  size?: number;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  weight?: "thin" | "light" | "regular" | "bold" | "fill" | "duotone";
}) {
  if (!name) return null;
  const Cmp = PHOSPHOR_ICONS[name];
  if (!Cmp) return null;
  return (
    <Cmp
      size={size}
      weight={weight}
      color={color}
      className={className}
      style={style}
    />
  );
}
